<?php
/*
Template Name: kent_test_template
*/

get_header();

$max = 100;

$params = array('cols'    => 4,               //Number of columns of images (aka Number of images per row)
				  'start'   => 0,               //The first photo index to show (aka skip some initially)
				  'max'     => $max,     //The max number of items to show
				  'swapHead'=> false,           //Swap the order of the 2 lines in the album header?
				  'hideHead'=> false,           //Hide the album header entirely?
				  'hideCaps'=> false,           //Hide the per-photo captions on the main listing?
				  'noLB'    => false,           //Suppress outputting the lightbox javascript?
				  'hideCred'=> false,           //Omit the "Generated by Facebook Photo Fetcher" footer (please don't :))
				  'rand'    => false,           //Randomly select n photos from the album (or from photos between "start" and "max")
				  'orderby' => 'normal');       //Can be "normal" or "reverse" (for now)
$itemwidth = $params['cols'] > 0 ? floor(100/$params['cols']) : 100;
$itemwidth -= (0.5/$params['cols']); //For stupid IE7, which rounds fractional percentages UP (shave off 0.5%, or the last item will wrap to the next row)

$access_token = get_option($fpf_opt_access_token);
//Get the name of the user/page whose ID we're searching
$search_uid = get_option($fpf_opt_last_uid_search);
$response = fpf_get("https://graph.facebook.com/$search_uid?access_token=$access_token&fields=name");
$search_name = $response->name;
if(!$search_name) $search_name = "(Unknown User)";

$i = 0;
$all_photos = array();

$response = fpf_get("https://graph.facebook.com/$search_uid/albums?access_token=$access_token&limit=999&fields=id,link,name");
$albums = $response->data;
$retVal['content'] = "<div class='gallery'>\n";

$aid = $albums->id;
$photos = fpf_get("https://graph.facebook.com/$search_uid/photos?access_token=$access_token&limit=$max&fields=name,source,picture");	
$photos = $photos->data;

$idx = 0;

foreach($photos as $photo)
{
	$caption = preg_replace("/\[/", "(", $photo->name);
	$caption = preg_replace("/\]/", ")", $caption);
	$caption = preg_replace("/\r/", "", $caption);
	$caption_with_br = htmlspecialchars(preg_replace("/\n/", "<br />", $caption));
	$caption_no_br = htmlspecialchars(preg_replace("/\n/", " ", $caption));
	$link = '<a rel="' . htmlspecialchars($album->link) . '" class="fbPhoto" href="'.$photo->source . '" title="'.$caption_with_br.' " ><img src="' . $photo->picture . '" alt="" /></a>';
	$retVal['content'] .= "<dl class='gallery-item' style=\"width:$itemwidth%\">";
	$retVal['content'] .= "<dt class='gallery-icon'>$link</dt>";
	if(!$params['hideCaps'])
	{
		$retVal['content'] .= "<dd class='gallery-caption'>";
		$retVal['content'] .= mb_substr($caption_no_br,0, 85) . (strlen($caption_no_br)>85?"...":"");
		$retVal['content'] .= "</dd>";
	}
	$retVal['content'] .= "</dl>\n";
	
	//Move on to the next row?
	if( $params['cols'] > 0 && ++$i % $params['cols'] == 0 ) $retVal['content'] .= "<br style=\"clear: both\" />\n\n";
}
if( $i%$params['cols'] != 0 ) $retVal['content'] .= "<br style=\"clear: both\" />\n\n";
$retVal['content'] .= "</div>\n";
if( !$params['hideCred'] )    $retVal['content'] .= "<span class=\"fpfcredit\">Generated by <i>Facebook Photo Fetcher 2</i></span>\n";

//Activate the lightbox when the user clicks a photo (only if the Lightbox plugin isn't already there)
if( !$params['noLB'] && !function_exists('lightbox_2_options_page') )
{
	$retVal['content'] .= '<script type="text/javascript">//<!--
	jQuery(document).ready(function() {
		jQuery("a[rel*=\''.$aid.'\']").fancybox({
			"transitionIn"	: "elastic",
			"transitionOut"	: "elastic",
			"titlePosition" : "inside",
			"titleFormat"	: function(title, currentArray, currentIndex, currentOpts)
			{
				return "<span id=\'fancybox-title-over\' style=\'background-image:none; text-align:left;\'>" + (title.length ? title : "") + "</span>";
			}
		});
	});'.
	"\n//--></script>\n";
}

echo $retVal['content'];

get_footer();

?>

